### PR TITLE
Add Airsonic apps

### PR DESCRIPTION
**Pull request by hschroedl**
As discussed, this provides an overview over apps available for Airsonic, see #9

I checked the apps available on the Subsonic App page, quite a lot of the links there are dead or lead to projects no longer maintained. The apps listed here are what's left.

### CODE REVIEW

**Comment by jooola** [comment]
Great thanks ! The table idea is pretty good !
Here is screenshot how it looks like on the website : 
[apps_airsonic.pdf](https://github.com/airsonic/documentation/files/1150653/apps_airsonic.pdf)
 
Still some apps are missing !

**Comment by jooola** [comment]
And one more thing, you only included the Play store apps !
Some apps are available on fdroid and are free ( dsub for example ).
Audinaut is also present on [fdroid](https://f-droid.org/) !

**Comment by hschroedl** [comment]
Thanks for the Input. 

Regarding missing apps: I added your suggestions (Dsub for FDroid, Clementine, Audinaut, Jamstash). Keep in mind that I did not add some apps present on the subsonic site deliberately, because they are no longer maintained/not working. 

Additional apps can still be added in the future via future pull request, I think this serves as a start :)

P.S. Am aware how it looks, use Jekyll on a weekly basis: `bundle exec jekyll serve` ;)

**Comment by jooola** [comment]
Thanks a lot , yeah this will be a start !
Merging this now

**Pull request merged**
